#--------------------------------------------------------------------------------------------
# Configuration for Generate genesis block, channel.tx and anchor peer using configtxgen tool
#--------------------------------------------------------------------------------------------
---
#-------------------------------------------------------------------------------
#   Capabilities
#-------------------------------------------------------------------------------
Capabilities:
    Global: &ChannelCapabilities
        V1_1: true

    Orderer: &OrdererCapabilities
        V1_1: true

    Application: &ApplicationCapabilities
        V1_2: true

#-------------------------------------------------------------------------------
#   Section: Organizations
#-------------------------------------------------------------------------------
Organizations:

    - &OrdererOrg
        Name: OrdererMSP
        # ID to load the MSP definition as
        ID: OrdererMSP
        AdminPrincipal: Role.ADMIN
        # MSPDir is the filesystem path which contains the MSP configuration
        MSPDir: crypto-config/ordererOrganizations/cievus.com/msp

    - &Client1
        Name: Client1MSP
        ID: Client1MSP
        MSPDir: crypto-config/peerOrganizations/client1.cievus.com/msp
        AdminPrincipal: Role.ADMIN
        AnchorPeers:
            - Host: peer0.client1.cievus.com
              Port: 7051

    - &Client2
        Name: Client2MSP
        ID: Client2MSP
        MSPDir: crypto-config/peerOrganizations/client2.cievus.com/msp
        AdminPrincipal: Role.ADMIN
        AnchorPeers:
            - Host: peer0.client2.cievus.com
              Port: 7051

    - &Client3
        Name: Client3MSP
        ID: Client3MSP
        MSPDir: crypto-config/peerOrganizations/client3.cievus.com/msp
        AdminPrincipal: Role.ADMIN
        AnchorPeers:
            - Host: peer0.client3.cievus.com
              Port: 7051

#-------------------------------------------------------------------------------
#   Orderer
#-------------------------------------------------------------------------------
Orderer: &OrdererDefaults

    OrdererType: kafka

    Addresses:
        - orderer1-safedoc.cievus.com:7050
        - orderer2-safedoc.cievus.com:7050
        - orderer3-safedoc.cievus.com:7050
    BatchTimeout: 300ms
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 102760448
        PreferredMaxBytes: 524288

    Kafka:
        # Brokers: A list of Kafka brokers to which the orderer connects
        # NOTE: Use IP:port notation
        Brokers:
            - kafka0:9092
            - kafka1:9092
            - kafka2:9092
            - kafka3:9092

    # Organizations is the list of orgs which are defined as participants on
    # the orderer side of the network
    Organizations:

#-------------------------------------------------------------------------------
#   Application
#-------------------------------------------------------------------------------
Application: &ApplicationDefaults

    # Organizations is the list of orgs which are defined as participants on
    # the application side of the network
    Organizations:

#-------------------------------------------------------------------------------
#   Profile
#-------------------------------------------------------------------------------
Profiles:

    Cievus-safedoc-Genesis:
        Orderer:
            <<: *OrdererDefaults
            OrdererType: kafka
            Addresses:
                - orderer1-safedoc.cievus.com:7050
                - orderer2-safedoc.cievus.com:7050
                - orderer3-safedoc.cievus.com:7050
            Organizations:
                - *OrdererOrg
        Consortiums:
            CievusConsortium:
                Organizations:
                    - *Client1
                    - *Client2
                    - *Client3
    Cievus-safedoc-channel:
        Consortium: CievusConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Client1
                - *Client2
                - *Client3
